export enum Context {
    AUTH_SERVICE = 'AUTH_SERVICE',
    PANEL_SERVICE = 'PANEL_SERVICE',
    TOAST_SERVICE = 'TOAST_SERVICE',
    GMAIL_OPERATION_SERVICE = 'GMAIL_OPERATION_SERVICE',
    ROUTER = "ROUTER",
}
