export enum Context {
    AUTH_SERVICE = 'AUTH_SERVICE',
    PANEL_SERVICE = 'PANEL_SERVICE',
    TOAST_SERVICE = 'TOAST_SERVICE',
    MESSAGE_ACTION_SERVICE = 'MESSAGE_ACTION_SERVICE',
    ROUTER = "ROUTER",
}
